name: sensors_plus_web
description: The web implementation of sensors_plus
version: 0.2.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SensorsPlugin
        fileName: sensors_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  sensors_plus_platform_interface:
    git:
      url: git@github.com:Lambda-Sense-Ltd/plus_plugins.git
      ref: sensor_plus_platform_interface-lds
      path: packages/sensors_plus_platform_interface
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2
  pedantic: ^1.9.2
